### ISSUE TITLE
Database file is missing 

### ISSUE THREAD

**Issue by Romanstha** [VSH30/Exam-Portal#1]
Can you provide me a database file ?

**Comment by VSH30** [comment]
> Can you provide me a database file ?

Sure, will upload it in 2 3 hours.

**Comment by VSH30** [comment]
You can check it now.

**Comment by Romanstha** [comment]
Thank you for your response
Can you please tell me what is admin and students login details?

**Comment by VSH30** [comment]
RNO = 1
PASS = 111
Use this for faculty login and then you can add students/tests/faculty members
